[package]
name = "aur-build-server"
version = "0.20.0"
edition = "2021"

[[bin]]
name = "aur-build-server"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

clap = { version = "4.5.4", features = ["derive"] }

warp = "0.3.7"
reqwest = { version = "0.12.4", features = ["blocking", "multipart", "json", "stream"] }

rand = "0.8.5"

chrono = { version = "0.4.38", features = ["serde"] }
regex = "1.10.5"

serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"

futures = "0.3.30"
futures-util = { version = "0.3.30", default-features = false, features = ["std", "sink"] }

log = { version = "0.4.21", features = ["serde"] }
simplelog = "0.12.2"

bytes = "1.6.1"
handlebars = "6.0.0"
anyhow = "1.0.86"

[dev-dependencies]
serial_test = "3.1.1"
