[package]
name = "aur-build-server"
version = "0.10.0"
edition = "2021"

[[bin]]
name = "aur-build-server"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

clap = { version = "4.4.11", features = ["derive"] }

warp = "0.3.6"
reqwest = { version = "0.11", features = ["blocking", "multipart", "json", "stream"] }

hyper = { version = "=0.14.28", features = ["full"] }

rand = "0.8.5"

chrono = { version = "0.4.31", features = ["serde"] }
regex = "1.10.2"

serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"

futures = "0.3.29"
futures-util = { version = "0.3.29", default-features = false, features = ["std", "sink"] }

simple-error = "0.3.0"

log = "0.4.20"
simplelog = "0.12.1"
bytes = "1.5.0"
