[package]
name = "aur-build-server"
version = "0.10.0"
edition = "2021"

[[bin]]
name = "aur-build-server"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

clap = { version = "4.5.4", features = ["derive"] }

warp = "0.3.6"
reqwest = { version = "0.12.2", features = ["blocking", "multipart", "json", "stream"] }

rand = "0.8.5"

chrono = { version = "0.4.35", features = ["serde"] }
regex = "1.10.4"

serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"

tokio = { version = "1.37.0", features = ["full"] }
tokio-stream = "0.1.15"

futures = "0.3.30"
futures-util = { version = "0.3.30", default-features = false, features = ["std", "sink"] }

simple-error = "0.3.0"

log = "0.4.21"
simplelog = "0.12.2"
bytes = "1.6.0"
