services:
  server:
    image: aur-build-server:local
    build:
      context: .
      dockerfile: Dockerfile
      target: server
      cache_from:
        - aur-build-server:local
    command: --log-level debug
    environment:
      - SIGN_KEY_PATH=/app/key.asc
    ports:
      - "8888:8888"
    volumes:
      - "./config_server.json:/app/config_server.json"
      - "./mount/logs:/app/logs"
      - "./mount/serve:/app/serve"
      - "./key.asc:/app/key.asc"
  worker:
    image: aur-build-worker:local
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
      cache_from:
        - aur-build-server:local
    command: --log-level debug
    volumes:
      - "./config_worker.json:/app/config_worker.json"
