[package]
name = "aur-build-cli"
version = "0.9.2"
edition = "2021"

[[bin]]
name = "aur-build-cli"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

chrono = { version = "0.4.31", features = ["serde"] }

reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
clap = { version = "4.4.11", features = ["derive"] }
colored = "2.1.0"
dialoguer = "0.11.0"
simple-error = "0.3.0"
homedir = "0.2.1"
