[package]
name = "aur-build-cli"
version = "0.10.0"
edition = "2021"

[[bin]]
name = "aur-build-cli"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

chrono = { version = "0.4.35", features = ["serde"] }

reqwest = { version = "0.11.25", features = ["blocking", "json"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
clap = { version = "4.5.2", features = ["derive"] }
colored = "2.1.0"
dialoguer = "0.11.0"
simple-error = "0.3.0"
homedir = "0.2.1"
