[package]
name = "aur-build-cli"
version = "0.10.0"
edition = "2021"

[[bin]]
name = "aur-build-cli"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }

chrono = { version = "0.4.38", features = ["serde"] }

reqwest = { version = "0.12.4", features = ["blocking", "json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
clap = { version = "4.5.4", features = ["derive"] }
colored = "2.1.0"
dialoguer = "0.11.0"
simple-error = "0.3.0"
homedir = "0.2.1"
cli-table = "=0.4.7"
