[package]
name = "aur-build-worker"
version = "0.9.2"
edition = "2021"

[[bin]]
name = "aur-build-worker"
path = "src/main.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }

clap = { version = "4.4.11", features = ["derive"] }

warp = "0.3.6"
reqwest = { version = "0.11", features = ["multipart", "json", "stream"] }

hyper = { version = "=0.14.28", features = ["full"] }

chrono = { version = "0.4.31", features = ["serde"] }

serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

tokio = { version = "1.35.1", features = ["full"] }
tokio-stream = "0.1.14"
tokio-tungstenite = "0.21.0"

futures = "0.3.29"
futures-util = { version = "0.3.29", default-features = false, features = ["std", "sink"] }

git2 = "0.18.1"

relative-path = "1.9.0"

log = "0.4.20"
simplelog = "0.12.1"

srcinfo = "1.1.0"

async-recursion = "1.0.5"

