apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-data
  namespace: aurbuild
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi